<Project>
    <PropertyGroup>
        <StaticWebAssetFingerprintingEnabled>false</StaticWebAssetFingerprintingEnabled>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <Version>0.1.0</Version>
    </PropertyGroup>
    
    <PropertyGroup Condition="'$(CI)' == 'true'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>
</Project>
