<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="YamlDotNet" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="settings/*.yaml"
                 TargetPath="settings/%(Filename)%(Extension)"
                 CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Titanite.Abstractions\Titanite.Abstractions.csproj" />
      <ProjectReference Include="..\Titanite.Core\Titanite.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <InternalsVisibleTo Include="Titanite.Catalog.Tests" />
    </ItemGroup>

</Project>
